language: scala

jdk:
  - oraclejdk8

script:
  - sbt scalafmtCheck +test

cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt/boot/"

before_cache:
  - find $HOME/.ivy2/cache/io.crashbox -depth -name "yamlesque*" -exec rm -r {} \;
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
